---
name: Lint Code Base

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check alphabetical order in file
        run: |
          cp README.md README.prev.md
          make
          diff README.prev.md README.md
        env:
          LANG: de_DE.UTF-8
          LC_ALL: de_DE.UTF-8

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_NATURAL_LANGUAGE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.x"

      - name: Install fortune
        run: sudo apt-get install fortune

      - name: Run make gen-fortune
        run: make gen-fortune

      - name: Get Date
        id: date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_OUTPUT

      - name: Get Short SHA
        id: sha
        run: echo "{sha}={$(git rev-parse --short HEAD)}" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        # only run this action if the branch is `main`:
        if: github.ref == 'refs/heads/main'
        #
        with:
          files: |
            output/flachwitze
            output/flachwitze.dat

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
          release_name: ${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
          draft: false
          prerelease: false
